### ISSUE TITLE
Error while testing demo_show

### ISSUE THREAD

**Issue by VbossEkat** [trobz/openerp-booking-chart#14]
Good afternoon,
I want to apply the module that you created, but ran into some errors. I corrected some of them myself, but I do not know what to do now. Screenshot attached.
Please, help.
![error demo](https://cloud.githubusercontent.com/assets/11025283/25483005/7c816480-2b6d-11e7-9300-b3c9e8a96300.png)

**Comment by anothingguy** [comment]
hi,
Are you using booking-chart version 8.0, right ?
From the screenshot, it seems that [twix.js](https://github.com/trobz/openerp-web-unleashed/blob/8.0/web_unleashed_extra/static/lib/moment-twix/twix.js) library in module `web_unleashed_extra` was not loaded properly, could you check this file was loaded or not.
and take look at console of Developer Tools to find more some abnormal error when loading `booking-chart `?

**Comment by VbossEkat** [comment]
Has earned after updating odoo. Thank you.

**Comment by jcdrubay** [comment]
@VbossEkat You should also look at https://github.com/OCA/web/tree/10.0/web_timeline which is maintained by OCA and available in version 10. It does not have exactly the same features, but it might suit your case.

**Comment by VbossEkat** [comment]
Thanks for the help - I'll check it out
