### ISSUE TITLE
Simple chart

### ISSUE THREAD

**Issue by difra** [trobz/openerp-booking-chart#3]
Hi,
is it possibile to use the openerp-booking-chart in order to display a simple task view through your wonderful chart? (without resources and without handling the sync between model and booking.resource) 
I checked a demo_task module, but I don't want to link any resources to my task.

Cheers.

**Comment by zazabe** [comment]
We did the choice to create a new model (booking.resource) to simply the model and provide a way to display any kind of models in the same booking chart in an abstract way. 

Displaying directly any model in the booking chart will over complicate the work to do on the client side to retrieve them, but I'm agree, it will simplify the booking chart configuration...

Anyhow, there's no plan to change this for now.
