### ISSUE TITLE
booking_chart and odoo

### ISSUE THREAD

**Issue by websavetnik** [trobz/openerp-booking-chart#5]
Can you tell me how to use your chart module in openerp V8, is it enough to change **openerp**.py file in your module or there is some work to be done od javascript

**Comment by zazabe** [comment]
Hi, sorry for my late answer.

We already have a 8.0 version, but we did some improvement and I still need to document them before publishing it:
- update dependencies (bootstrap, underscore and marionette)
- booking chart by hours / by days
- timezone support
- some refactoring 
- bug fix

I hope I can publish the new version of the booking chart and web unleash at the beginning of march.

**Comment by zazabe** [comment]
Hi, 
I'm happy to announce that the version 8.0 is now available. You can give a try to the `demo_show` module to see new features like the booking chart by hours.

**Comment by cunguito** [comment]
I installed it in windows sucessfully, but in linux, i get this error:

Uncaught TypeError: Cannot read property 'module' of undefined
openerp.unleashed.module
