### ISSUE TITLE
Multiple charts

### ISSUE THREAD

**Issue by Shide** [trobz/openerp-booking-chart#6]
Hello,
first of all, thanks for your awesome chart. It's incredible.
I've implemented two modules with one chart on each module. When I change between charts (they are on different menu items), only the first chart who click on it displays the records. 
In order to show the records on the second chart, I should refresh the page (for destroying the chart object).
I've tried to add a condition to destroy the object and resend the action when the chart model changes on init/start method of booking.js, but always throws an error, goes to infinite recursively or nothing happens.

```
//defined as global variable on top:
last_view_model = 0;

do_reload: function(){
  if (this.getParent() != undefined){
    var view_manager = this.getParent(), action_manager = view_manager.getParent();
    if (last_view_model != view_manager.action.res_model){
      last_view_model = view_manager.action.res_model;
      this.destroy();
      action_manager.do_action(view_manager.action);
    }
  }
},
```

I think I should destroy the UnleashedView instead the custom view.
Thanks for your time and any hints to continue?

**Comment by Shide** [comment]
Well, the problem was that the booking_chart module don't catch the real model to render.
I made this patch on the code, but the real problem is one level higher. 

![captura de pantalla 2015-02-13 a la s 10 30 28](https://cloud.githubusercontent.com/assets/1162050/6185197/ecd6abfe-b36b-11e4-911c-4a99d0cffac5.png)

I hope this helps to improve your module and other people.

**Comment by zazabe** [comment]
Hi, 

About your first post, we already used multiple booking chart on some projects without any issue, and switching from one booking chart to another will destroy the previous one normally... 

About your solution, from what i understand, you mean that the collection `model_name` is different than the `model_name` on each item, seems to be a bug on `BaseCollection` and/or `BaseModel` from web unleashed.

I will try to reproduce the issue by creating 2 booking charts with different model for their items and see what happen.

Thanks for your feedback!

**Comment by zazabe** [comment]
The version 8.0 of the booking chart has a demo (`demo_show` module) with 2 booking charts, I didn't notice any bug when i switch from one to the other so i will consider this issue as fixed, tell me if you still have it.
