### ISSUE TITLE
add booking from chart

### ISSUE THREAD

**Issue by yelizariev** [trobz/openerp-booking-chart#8]
Is there a way to add booking (resource in your terms I guess) from chart view or chart is read-only?
Do you have plan to implement it? Is it easy to do?

**Comment by jcdrubay** [comment]
At this time, it is readonly.
We currently have no plan to implement.
For the question "Is it easy to do?", I let @zazabe answer you.

**Comment by zazabe** [comment]
Not currently but you can add a event listener on the full booking chart view, then open a form view to create the resource, then refresh the booking chart...
